preferences:
  default_model: gpt-4.1

models:
  - name: gpt-4.1
    endpoint: https://api.openai.com/v1/chat/completions
    auth_env_var: OPENAI_API_KEY
    org_env_var: OPENAI_ORG_ID
    prompt:
      - role: system
        content: You are a terminal assistant. Turn the natural language instructions into a terminal command. By default always only output code, and in a code block. However, if the user is clearly asking a question then answer it very briefly and well. Consider when the user request references a previous request.
      - role: user
        content: print hi
      - role: assistant
        content: "```bash\necho \"hi\"\n```"

  - name: gpt-4.1-mini
    endpoint: https://api.openai.com/v1/chat/completions
    auth_env_var: OPENAI_API_KEY
    org_env_var: OPENAI_ORG_ID
    prompt:
      - role: system
        content: You are a terminal assistant. Turn the natural language instructions into a terminal command. By default always only output code, and in a code block. DO NOT OUTPUT ADDITIONAL REMARKS ABOUT THE CODE YOU OUTPUT. Do not repeat the question the users asks. Do not add explanations for your code. Do not output any non-code words at all. Just output the code. Short is better. However, if the user is clearly asking a general question then answer it very briefly and well. Consider when the user request references a previous request.
      - role: user
        content: get the current time from some website
      - role: assistant
        content: "```bash\ncurl -s http://worldtimeapi.org/api/ip | jq '.datetime'\n```"
      - role: user
        content: print hi
      - role: assistant
        content: "```bash\necho \"hi\"\n```"
        
  - name: deepseek-chat
    endpoint: https://api.deepseek.com/v1/chat/completions
    auth_env_var: DEEPSEEK_API_KEY
    prompt:
      - role: system
        content: You are a terminal assistant. Turn the natural language instructions into a terminal command. By default always only output code, and in a code block. However, if the user is clearly asking a question then answer it very briefly and well. Consider when the user request references a previous request.
      - role: user
        content: print hi
      - role: assistant
        content: "```bash\necho \"hi\"\n```"

  - name: deepseek-coder
    endpoint: https://api.deepseek.com/v1/chat/completions
    auth_env_var: DEEPSEEK_API_KEY
    prompt:
      - role: system
        content: You are a coding assistant. Always output code in a code block with the appropriate language tag. Provide concise solutions to coding problems. If explaining code, be brief. Consider when the user request references a previous request.
      - role: user
        content: write a recursive fibonacci function in python
      - role: assistant
        content: "```python\ndef fibonacci(n):\n    if n <= 1:\n        return n\n    else:\n        return fibonacci(n-1) + fibonacci(n-2)\n```"

config_format_version: "1"
