name: Release Binaries

on:
  push:
    tags:
      - "v*"

jobs:
  build:
    name: Build and Release
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.21"

      - name: Set release version
        run: echo "RELEASE_VERSION=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV

      - name: Build binaries
        run: |
          # Create a directory for binaries
          mkdir -p ./dist

          # Build for Windows
          GOOS=windows GOARCH=amd64 go build -o ./dist/shell-ai-${{ env.RELEASE_VERSION }}-windows-amd64.exe main.go

          # Build for macOS
          GOOS=darwin GOARCH=amd64 go build -o ./dist/shell-ai-${{ env.RELEASE_VERSION }}-darwin-amd64 main.go
          GOOS=darwin GOARCH=arm64 go build -o ./dist/shell-ai-${{ env.RELEASE_VERSION }}-darwin-arm64 main.go

          # Build for Linux
          GOOS=linux GOARCH=amd64 go build -o ./dist/shell-ai-${{ env.RELEASE_VERSION }}-linux-amd64 main.go
          GOOS=linux GOARCH=arm64 go build -o ./dist/shell-ai-${{ env.RELEASE_VERSION }}-linux-arm64 main.go

          # Make binaries executable
          chmod +x ./dist/*

          # Create checksums
          cd ./dist && sha256sum * > checksums.txt

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          name: "ShellAI ${{ env.RELEASE_VERSION }}"
          draft: false
          prerelease: false
          generate_release_notes: true
          files: |
            ./dist/*
